### ISSUE TITLE
AddEditPoll Forum poll option value single space character

### ISSUE THREAD

**Issue by meshuggahtas** [TASVideos/tasvideos#1164]
**Poll option being a single space character results in Internal Server Error**

1. Go to a forum thread and click on Poll
2. Add a poll option with a single space character and press Add
3. Internal Server Error page for client, VS Code exception text:
```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in TASVideos.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at TASVideos.Pages.Forum.Topics.Models.PollCreateModel.<>c.<get_OptionsAreValid>b__19_1(String o) in [C:\Users\Administrator\tasvideosVSCodeDotNET60\tasvideos\TASVideos\Pages\Forum\Topics\Models\PollCreateModel.cs]():line 27
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at TASVideos.Pages.Forum.Topics.Models.PollCreateModel.get_OptionsAreValid() in [C:\Users\Administrator\tasvideosVSCodeDotNET60\tasvideos\TASVideos\Pages\Forum\Topics\Models\PollCreateModel.cs]():line 26
   at TASVideos.Pages.Forum.Topics.Models.PollCreateModel.get_IsValid() in [C:\Users\Administrator\tasvideosVSCodeDotNET60\tasvideos\TASVideos\Pages\Forum\Topics\Models\PollCreateModel.cs]():line 21
   at Microsoft.Extensions.Internal.PropertyHelper.CallNullSafePropertyGetter[TDeclaringType,TValue](Func`2 getter, Object target)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationEntry.get_Model()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult, Object container)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__8.MoveNext()
```

edit: Relevant line of code
https://github.com/TASVideos/tasvideos/blob/3cb375c178bbf4eb6a8cae28de69c7e50c95cb1f/TASVideos/Pages/Forum/Topics/Models/PollCreateModel.cs#L26

**Comment by adelikat** [comment]
I think this has been fixed.  Can't reproduce and the code looks like it would never NRE.  My guess was we addressed some nullability issues in other parts of the code that indirectly fixed this
