### ISSUE TITLE
Some userfiles give system error

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/tasvideos#1444]
https://tasvideos.org/UserFiles/ForUser/feos
https://tasvideos.org/UserFiles/Game/707
https://tasvideos.org/UserFiles/Info/638014279980501493
https://tasvideos.org/UserFiles/Game/2711

while others are okay
https://tasvideos.org/UserFiles/ForUser/KusogeMan
https://tasvideos.org/UserFiles/Info/638013987801154354
https://tasvideos.org/UserFiles/Info/638015394357741990

**Comment by Masterjun3** [comment]
Error message:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'PageData cannot be null.')
   at TASVideos.TagHelpers.WikiMarkup.TASVideos.WikiEngine.AST.IWriterHelper.RunViewComponentAsync(TextWriter w, String name, IReadOnlyDictionary`2 pp) in C:\Users\Masterjun\Desktop\newtasv\TASVideos\TagHelpers\WikiMarkupTagHelper.cs:line 46
   at TASVideos.WikiEngine.AST.Module.WriteHtmlAsync(TextWriter w, WriterContext ctx) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.WikiEngine\NodeImplementations.cs:line 427
   at TASVideos.WikiEngine.AST.Element.WriteHtmlAsync(TextWriter w, WriterContext ctx) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.WikiEngine\NodeImplementations.cs:line 215
   at TASVideos.WikiEngine.Util.RenderHtmlAsync(String content, TextWriter w, IWriterHelper h) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.WikiEngine\Util.cs:line 60
   at TASVideos.TagHelpers.WikiMarkup.ProcessAsync(TagHelperContext context, TagHelperOutput output) in C:\Users\Masterjun\Desktop\newtasv\TASVideos\TagHelpers\WikiMarkupTagHelper.cs:line 34
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at TASVideos.Pages.Shared.Pages_Shared__UserFileInfo.<>c__DisplayClass37_0.<<ExecuteAsync>b__8>d.MoveNext() in C:\Users\Masterjun\Desktop\newtasv\TASVideos\Pages\Shared\_UserFileInfo.cshtml:line 81
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at TASVideos.Pages.Shared.Pages_Shared__UserFileInfo.<>c__DisplayClass37_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\Users\Masterjun\Desktop\newtasv\TASVideos\Pages\Shared\_UserFileInfo.cshtml:line 80
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at TASVideos.Pages.Shared.Pages_Shared__UserFileInfo.ExecuteAsync() in C:\Users\Masterjun\Desktop\newtasv\TASVideos\Pages\Shared\_UserFileInfo.cshtml:line 17
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at TASVideos.Pages.UserFiles.Pages_UserFiles_ForUser.ExecuteAsync() in C:\Users\Masterjun\Desktop\newtasv\TASVideos\Pages\UserFiles\ForUser.cshtml:line 15
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at TASVideos.Extensions.ApplicationBuilderExtensions.<>c.<<UseMvcWithOptions>b__4_0>d.MoveNext() in C:\Users\Masterjun\Desktop\newtasv\TASVideos\Extensions\ApplicationBuilderExtensions.cs:line 59
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by nattthebear** [comment]
I guess this was wrong?  https://github.com/TASVideos/tasvideos/blob/f04a1786971cdfb25c9c1c666326a810f202261e/TASVideos/TagHelpers/WikiMarkupTagHelper.cs#L44

@adelikat 

I'm not sure how this all shakes out... are userfiles not pages and so don't have a pagedata?

**Comment by adelikat** [comment]
I'll take a look when I get a chance, I'm guessing I recently broke this with that major refactor
