### ISSUE TITLE
ForumEngine throws exception on empty urls

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/tasvideos#1885]
Markup with:
```
[url][/url]
```

Exception is this:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TASVideos.Common.UriString.IsToExternalDomain(ReadOnlySpan`1 uri) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.Common\UriString.cs:line 11
   at TASVideos.ForumEngine.Element.AddStockAttrsToHyperlink(HtmlWriter w, String targetURI) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 80
   at TASVideos.ForumEngine.Element.WriteHyperlink(HtmlWriter w, String labelText, String targetURI, ValueTuple`2[] attrs) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 96
   at TASVideos.ForumEngine.Element.WriteHref(HtmlWriter w, IWriterHelper h, Func`2 transformUrl, Func`2 transformUrlText) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 209
   at TASVideos.ForumEngine.Element.WriteHtml(HtmlWriter w, IWriterHelper h) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 347
   at TASVideos.ForumEngine.Element.WriteChildren(HtmlWriter w, IWriterHelper h) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 135
   at TASVideos.ForumEngine.Element.WriteHtml(HtmlWriter w, IWriterHelper h) in C:\Users\Masterjun\Desktop\newtasv\TASVideos.ForumEngine\Node.cs:line 525
   at TASVideos.TagHelpers.ForumMarkupTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in C:\Users\Masterjun\Desktop\newtasv\TASVideos\TagHelpers\ForumMarkupTagHelper.cs:line 19
...
```

Example post where this happens:
https://tasvideos.org/Forum/Topics/998?CurrentPage=5&PageSize=25&Sort=CreateTimestamp

The exact markup there (kind of poorly formatted):
```
normally, a link is done as follows:
[color=red][b][url][/b][/color]http://tasvideos.org/[color=red][b][/url][/b][/color] 
gives you this: [url]http://tasvideos.org/[/url]
If you do this instead:
[color=red][b][url=http://tasvideos.org/][/b][/color]Link to Nesvideos[color=red][b][/url][/b][/color]
then you'll get [url=http://tasvideos.org/]Link to Nesvideos[/url] clickable, sending you to that website, without showing a (possibly) huge long url.  Similar to the <A HREF> tag in HTML.  Not a big deal since we hit a new page, but for future reference.  Also, you don't have to put the part after the /###/ of the url on DeHackEd's microstorage.  It still links to the same page.
[size=65%][Edited by Bisqwit: real brackets][/size]
```

**Comment by nattthebear** [comment]
https://github.com/TASVideos/tasvideos/blob/main/TASVideos.Common/UriString.cs#L11

Can't access `uri[0]` without a length check first.  @YoshiRulz

**Comment by YoshiRulz** [comment]
The implementation actually dates back to at least https://github.com/TASVideos/tasvideos/commit/5a02afce436244ca6d04cbe99ea5e5447797808b, but it seems the bug is only showing up now because this is an additional call-site.
I believe browsers (e.g. with `location.assign`) treat an empty string the same as `./`, which would not be not an external link.
```diff
// impl.
public static bool IsToExternalDomain(ReadOnlySpan<char> uri)
-	=> !(uri[0] is '#' || (uri[0] is '/' && (uri.Length < 2 || uri[1] is not '/')));
+	=> uri.Length >= 1 && !(uri[0] is '#' || (uri[0] is '/' && (uri.Length < 2 || uri[1] is not '/')));

// unit test
-#if false // throws
 	[DataRow(false, ""/*empty string*/)]
-#endif
```

**Comment by nattthebear** [comment]
That diff makes sense to me :+1:

**Comment by Masterjun3** [comment]
This issue still happens.
