### ISSUE TITLE
Wiki Diff - possible to throw an Exception

### ISSUE THREAD

**Issue by adelikat** [TASVideos/tasvideos#949]
2 prod examples of an InvalidOperationException.  Probably some junk values, but better is to prevent the exception and subsequent drain on resources

```
{
    "Timestamp": "2022-01-13T00:07:38.9363737+00:00",
    "Level": "Error",
    "MessageTemplate": "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms",
    "Exception": "System.InvalidOperationException: Page \"HomePages/Memory/Judging\" or revisions 0-1 could not be found
   at TASVideos.Pages.Wiki.DiffModel.GetPageDiff(String pageName, Int32 fromRevision, Int32 toRevision) in /home/tasvideos/tasvideos/TASVideos/Pages/Wiki/Diff.cshtml.cs:line 77
   at TASVideos.Pages.Wiki.DiffModel.OnGet() in /home/tasvideos/tasvideos/TASVideos/Pages/Wiki/Diff.cshtml.cs:line 48
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at TASVideos.Extensions.ApplicationBuilderExtensions.<>c.<<UseMvcWithOptions>b__4_0>d.MoveNext() in /home/tasvideos/tasvideos/TASVideos/Extensions/ApplicationBuilderExtensions.cs:line 71
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)",
    "Properties": {
        "RequestMethod": "GET",
        "RequestPath": "/Wiki/Diff?path=HomePages%2FMemory%2FJudging&fromRevision=0&toRevision=1",
        "StatusCode": 500,
        "Elapsed": 2.729809,
        "SourceContext": "Serilog.AspNetCore.RequestLoggingMiddleware"
    },
    "Renderings": {
        "Elapsed": [
            {
                "Format": "0.0000",
                "Rendering": "2.7298"
            }
        ]
    }
}
{
    "Timestamp": "2022-01-13T00:07:38.9664598+00:00",
    "Level": "Error",
    "MessageTemplate": "An unhandled exception occurred.",
    "Exception": "System.InvalidOperationException: Page \"HomePages/Memory/Judging\" or revisions 0-1 could not be found
   at TASVideos.Pages.Wiki.DiffModel.GetPageDiff(String pageName, Int32 fromRevision, Int32 toRevision) in /home/tasvideos/tasvideos/TASVideos/Pages/Wiki/Diff.cshtml.cs:line 77
   at TASVideos.Pages.Wiki.DiffModel.OnGet() in /home/tasvideos/tasvideos/TASVideos/Pages/Wiki/Diff.cshtml.cs:line 48
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at TASVideos.Extensions.ApplicationBuilderExtensions.<>c.<<UseMvcWithOptions>b__4_0>d.MoveNext() in /home/tasvideos/tasvideos/TASVideos/Extensions/ApplicationBuilderExtensions.cs:line 71
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at TASVideos.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context, IWebHostEnvironment env, ILogger`1 logger) in /home/tasvideos/tasvideos/TASVideos/Middleware/ExceptionHandlingMiddleware.cs:line 32",
    "Properties": {
        "SourceContext": "TASVideos.Middleware.ErrorHandlingMiddleware",
        "RequestId": "0HMELUC16VPGC:00000002",
        "RequestPath": "/Wiki/Diff",
        "ConnectionId": "0HMELUC16VPGC"
    }
}
```

**Comment by Masterjun3** [comment]
Apparently the exception is thrown intentionally.
https://github.com/TASVideos/tasvideos/blob/fa5a196589fcd312d50c924cef796fd95a253cda/TASVideos/Pages/Wiki/Diff.cshtml.cs#L64-L67
